### PR TITLE
SQL script finished

### PR DESCRIPTION
**Pull request by Rbb93**

### CODE REVIEW

**Review by hectorAlarcon — CHANGES_REQUESTED** [review]
Some mock values must be inserted inside the script. 
Every table must have at least 2 rows of mock data. 
This data should be inserted at the end of the file, after an SQL commentary about mock data.

**Comment by oriolOrnaque** [comment]
The travis scripts and the tests have changed recently and, therefore, a new check must be done for the build to be acceptable. Please, add the changes requested by Hector and trigger a new build with the new changes.

**Review by hectorAlarcon — CHANGES_REQUESTED** [review]
The design doesn't match the requirements needed. 
(Example of unmatched requirements : items have extras , such as drinks, sauces, etc with its price. So there must be some relation between items and its extra plus its price. And if a extra is mandatory should be stored too ) 
Check the new User Story's acceptance criteria.

**Comment by oriolOrnaque** [comment]
El travis reporta este error:
qwe

**Comment by Rbb93** [comment]
-Añadidas tablas extra_item y order_extraitem para añadir la relacion entre un item y sus extras y en los pedidos
-bit visible/invisible a un item añadido
-Eliminadas las tablas de allergen y allergen_items para seguir el prototipo de ubereats, donde hacen link a una tabla de allergenos de su web en un pdf donde desglosan alergenos en cada plato, y si no tienen esta tabla, hay un mensaje de avertencia para el caso de link vacio: "Alergias Alimentarios o necesidades dietéticas especiales: Antes de realizar su pedido, contacte directamente con el restaurante"

**Comment by oriolOrnaque** [comment]
Travis OK. Si Hector le da luz verde a los requirements, por mi ya se puede subir al main

**Pull request merged**
